# Generated by Django 3.2.2 on 2021-05-13 02:20

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='update date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('image', stdimage.models.StdImageField(upload_to='products', verbose_name='image')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='description')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
