# Generated by Django 3.2.2 on 2021-06-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='update date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('service', models.CharField(max_length=100, verbose_name='service')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('icon', models.CharField(choices=[('icon-phone', 'Phone'), ('icon-instagram', 'Instagram'), ('icon-email', 'Email')], max_length=14, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Informação para contato',
                'verbose_name_plural': 'Informações para contato',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=2, max_length=5, verbose_name='size'),
            preserve_default=False,
        ),
    ]
