# Generated by Django 3.2.2 on 2021-06-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_info_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='icon',
            field=models.CharField(choices=[('icon-email', 'Email'), ('icon-instagram', 'Instagram'), ('icon-phone', 'Phone')], max_length=14, verbose_name='icon'),
        ),
    ]
