# Generated by Django 3.2 on 2021-07-09 19:15

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_info_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='icon',
            field=models.CharField(choices=[('icon-email', 'Email'), ('icon-phone', 'Phone'), ('icon-instagram', 'Instagram')], max_length=14, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='image'),
        ),
    ]
