# Generated by Django 3.2 on 2021-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210709_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Contact information'},
        ),
        migrations.AlterField(
            model_name='info',
            name='icon',
            field=models.CharField(choices=[('icon-instagram', 'Instagram'), ('icon-phone', 'Phone'), ('icon-email', 'Email')], max_length=14, verbose_name='icon'),
        ),
    ]
